### ISSUE TITLE
Can amdgpu-monitor --log with local time?

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#26]
The *amdgpu-monitor --log* option prints monitor readings to file using GMT. Is there a way to have it report system time (local time) instead?

**Comment by Ricks-Lab** [comment]
> The _amdgpu-monitor --log_ option prints monitor readings to file using GMT. Is there a way to have it report system time (local time) instead?

I have been very busy lately, so it takes time to get back to the project.  I have been digging into this request, and there appears to be many complications.  I think best practice is to store all times in UTC and display in local, but working with timezones appears complex.  In addition, when reading back time info in plot utilities, times get converted into matplotlib times.  At this point, I don't see an easy solution, but I will continue to research it.

**Comment by Ricks-Lab** [comment]
@csecht 
I found a simpler approach and made changes to master.  Let me know of any issues.

**Comment by csecht** [comment]
Yes, that works. Nice. Thanks.

**Comment by Ricks-Lab** [comment]
Seems like I did not commit my final version. The final version implements local time throughput the project when *--ltz* is specified.  Updated readme and minor version number.
