### ISSUE TITLE
PPM table change in amdgpu 19.3 drivers

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#28]
I just upgraded my amdgpu driver package from 18.5 to 19.3 and notice a change in the ppm tables. They have added a *BOOTUP_DEFAULT* option at state 0, which adds 1 to the indices of the previous modes. Anyone that has a pac_writer script set to run at startup may need to update the script to the correct performance mode.  My new ppm table looks like this:
```
Card: /sys/class/drm/card1/device/
Power Performance Mode: manual
  0:  BOOTUP_DEFAULT                 -                 -                 -                 -                 -                 -
  1:  3D_FULL_SCREEN                 0               100                30                 0               100                10
  2:    POWER_SAVING                10                 0                30                 -                 -                 -
  3:           VIDEO                 -                 -                 -                10                16                31
  4:              VR                 0                11                50                 0               100                10
  5:         COMPUTE                 0                 5                30                 0               100                10
  6:          CUSTOM                 -                 -                 -                 -                 -                 -
 -1:            AUTO              Auto
```
Another difference I noticed with the new driver package is that my card indices have changed. Card 0 and Card 1 are now Card 1 and Card2.

**Comment by Ricks-Lab** [comment]
I noticed that I can only get to the 19.30 download if I select the new 5700 GPU and the readme says it is only for the new GPU.  Since I don't have a 5700, I have not tried 19.30.

Maybe a good way to handle this is to make a new section for the start-up script instructions in the user guide and start with a caution statement that changes in HW or Drivers will cause problems unless new pac files are generated.

**Comment by csecht** [comment]
Okay, good idea, I’ll work on updating the user guide.

Ha, yeah, I see what you mean about 19.3 Release Notes saying that only the 5700s are supported. I’m embarrassed to say I didn’t read that readme before the download. According to the AMD driver menus, I should have gone with the 19.2 driver stack for my current GPUs. Guess I got lucky this time. Oddly though, on the day I did the 19.3 download, I didn’t get the full pull-down menu option and don’t recall specifically choosing the 5700 family option (or any GPU family option); that’s not the case today though when I went back to check. Oh well, 19.3 is working, so I’ll stick with it.

**Comment by Ricks-Lab** [comment]
Could be that it was only tested for the 5700, but I will wait for an official release.

**Comment by csecht** [comment]
On my RX 570 cards, it seems that task completion times are ~1-2%  (~10 sec) faster with the 19.3 drivers compared to the 18.5 drivers. I see no difference with my RX 460 and RX560 cards. The updated Master correctly reports installation of the All-Open driver stack, so I'll close this out.
