### ISSUE TITLE
amdgpu-ls driver check and warning needs editing

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#30]
From the recent Master, from *amdgpu-ls* I get the warning:
```
Command '['dpkg', '-l', 'amdgpu-pro']' returned non-zero exit status 1.
Warning: amdgpu drivers not may not be installed.
```
True, I don't have *amdgpu-pro* installed, but *amdgpu* is:
```
~/Desktop/amdgpu-utils$ dpkg -l amdgpu
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version            Architecture       Description
+++-=================-==================-==================-=========================================
ii  amdgpu            19.30-838629       amd64              Meta package to install amdgpu components.
```
Shouldn't the driver check also include the amdgpu All-Open stack as well as the Pro stack?

**Comment by Ricks-Lab** [comment]
For some reason, 19.20 didn't show anything for amdgpu, so I made some changes to check for amdgpu-core, amdgpu, and amdgpu-pro.  Looks like amdgpu is back for 19.30, but I need to improve the robustness of the latest approach.

**Comment by Ricks-Lab** [comment]
I have made some changes that should be more robust.  I checked on 19.30 download, but it says that it is fop 5700 only, so I did not install it.  Let me know of any issues.

**Comment by csecht** [comment]
I was thinking of getting a 5700, but haven’t yet.  I never installed 19.1, but have found no problems running 19.30 with my current RX460, 560, 570s.

**Comment by csecht** [comment]
And yes, with the new master I no longer get then "no driver" warning, just the usual all-okay:
```
AMD Wattman features enabled: 0xffff7fff
amdgpu version: 19.30-838629
2 AMD GPUs detected, 2 may be compatible, checking...
2 are confirmed compatible.
```

**Comment by Ricks-Lab** [comment]
Thanks for confirming.
