### ISSUE TITLE
fail more nicely on machines with no AMD card

### ISSUE THREAD

**Issue by smoe** [Ricks-Lab/amdgpu-utils#37]
Hello,
I ran on my virtualbox machine and got
```
amdgpu-ls
amdgpu-utils non-compatible driver: driver=vboxvideo latency=0
Error in environment. Exiting...
```
same for
```
$ amdgpu-monitor 
amdgpu-utils non-compatible driver: driver=vboxvideo latency=0
Error in environment. Exiting...
```
Have not tried the others. But>
```
$ amdgpu-chk 
Using python 3.7.4
           Python version OK. 
Using Linux Kernel4.20.0-trunk-amd64
           OS kernel OK. 
```
My initial thought was that I was just missing a setting among the environment variables.  Maybe there is something more user-friendly to say that there is no driver installed that could possibly run AMD cards? And an interpretation of lspci suggesting that there is nothing installed hardware-wise either?

**Comment by Ricks-Lab** [comment]
All of my systems have AMD GPU's installed, so I have not seen this case.  The behavior I was expecting was to list the number of AMD GPUs, number of compatible AMD GPU's, The version of the driver 'amdgpu', which is required for the utils to work.  It should also display the featuremask value and if it supports Wattman like utilities, including this one.  

There may be some other issue triggering the 'Error in environment'.  I will have some time to dig into this over the weekend.

**Comment by Ricks-Lab** [comment]
I have added the following message:
```
amdgpu-utils non-compatible driver: driver=amdgpu latency=0
amdgpu-utils requires AMD's 'amdgpu' driver package in order to function.
Error in environment. Exiting...
```
I also update amdgpu-chk to include driver check.

This change is committed on master.  Let me know of any feedback.
