### ISSUE TITLE
Review of man pages

### ISSUE THREAD

**Issue by Ricks-Lab** [Ricks-Lab/amdgpu-utils#43]
I have been preparing a setup of man pages for use with a potential debian install package.  I have posted a nearly complete version of the [here](https://github.com/Ricks-Lab/amdgpu-utils/tree/master/man).  Please review and let me know if you see any issues?

The format is groff and they can be viewed with 
```
man -l filename
```

**Comment by Ricks-Lab** [comment]
@csecht 
Can you help to review the man pages I posted?  It would be good to have your perspective.  Plus you always seem to catch many errors.  Thanks!

**Comment by csecht** [comment]
I'll be glad to give it a look today.

**Comment by csecht** [comment]
The man pages look good. I made pull requests for simple edits on two of the files. 
Should I go over the User Guide?

**Comment by Ricks-Lab** [comment]
> The man pages look good. I made pull requests for simple edits on two of the files.
> Should I go over the User Guide?

Thanks for checking the man pages.  I have merged your changes.  In the User Guide, I had only changed the version number and the feature mask.  I found some posting indicating the original value could have issues for newer cards.
