### ISSUE TITLE
Ubuntu upgrade broke amdgpu-pac?

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#45]
The first cold restart I did after an Ubuntu upgrade with Linux kernel 5.0.0.31, *amdgpu-pac* was no longer able to set p-states, and my RX570's were crunching E@H at a p-state of 2 at full 120 W power and running very hot.  I had been using the default Linux 5.0 drivers with only OpenCL loaded from the 19.2 AMDGPU package. After installing the latest 19.3 (August 2019) AMDGPU package, *amdgpu-pac* is once again fully functional and the GPUs are running normally.  So, not an issue with amdgpu-utils, but a heads-up about upgrading Linux drivers.

**Comment by Ricks-Lab** [comment]
I am also running 5.0.0.31, but I did not encounter the same problem.  I am running 19.30 amdgpu driver, so maybe just a compatibility issue with 19.2.
