### ISSUE TITLE
feature request: monitor and set fans

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#5]
For cards with air coolers, it would be great to be able to monitor fan RPM and %max and to be able to set fan speeds (as a percentage of max).  For the RX460 and RX570 cards I have, AMD's default fan setting can make things a bit toasty under full loads.

**Comment by Ricks-Lab** [comment]
Thanks for the enhancement request. This will be targeted for v2.1.0 release.

**Comment by Ricks-Lab** [comment]
Just created new branch for this work:
https://github.com/Ricks-Lab/amdgpu-utils/tree/v2.1.0-Features

**Comment by Ricks-Lab** [comment]
@csecht  I have implemented the capability of reading all fan data and displaying with amdgpu-ls option.  Please check it out and let me know if it makes sense.  On my waterblocked cards, fan speeds show as all Zero.

**Comment by Ricks-Lab** [comment]
@csecht I have implemented write fan speed.  No way I can test it so please provide feedback.  Thanks!

**Comment by csecht** [comment]
Yes, good, that works.

$ ./amdgpu-ls | grep 'Model\|Fan'
Card Model:  Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560] (rev cf)
Short Card Model:  RX 460/560D / Pro 450/455/460/555/560
Fan Enable: 0
Fan PWM Mode: [2, 'Dynamic']
Current Fan PWM (%): 18.823529411764707
Current Fan Speed (rpm): 1472
Fan Target Speed (rpm): 1472
Fan Speed Range (rpm): [0, 6000]
Fan PWM Range (%): [0.0, 100.0]
Card Model:  Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev ef)
Short Card Model:  RX 470/480/570/570X/580/580X
Fan Enable: 0
Fan PWM Mode: [2, 'Dynamic']
Current Fan PWM (%): 53.72549019607843
Current Fan Speed (rpm): 2162
Fan Target Speed (rpm): 2162
Fan Speed Range (rpm): [0, 3800]
Fan PWM Range (%): [0.0, 100.0]

# Maybe round fan speed value to the integer?  But, hey, 13 decimal places do fit in the card columns, lol.

$ ./amdgpu-monitor 
┌─────────────┬────────────────┬────────────────┐
│Card #       │card1           │card0           │
├─────────────┼────────────────┼────────────────┤
│Model        │ RX 460/560D / P│ RX 470/480/570/│
│Load %       │100             │100             │
│Power (W)    │43.244          │100.086         │
│Power Cap (W)│44.0            │100.0           │
│T (C)        │74.0            │75.0            │
│VddGFX (mV)  │856             │1000            │
│Fan Spd (%)  │18.8235294117647│54.9019607843137│
│Sclk (MHz)   │1102Mhz         │1208Mhz         │
│Sclk Pstate  │4               │5               │
│Mclk (MHz)   │1750Mhz         │1750Mhz         │
│Mclk Pstate  │1               │2               │
│Perf Mode    │0-3D_FULL_SCREEN│0-3D_FULL_SCREEN│
└─────────────┴────────────────┴────────────────┘

**Comment by csecht** [comment]
After raising fan speeds in amdgpu-pac and manually executing the shell scripts, there was no change; fans remained at their default settings.  
Seeing this from the -ls module:

Fan PWM Mode: [2, 'Dynamic']

does the Mode need to be set to Manual for any override to take hold?  I'm just guessing here.

**Comment by csecht** [comment]
Yes! The fan speed readings are correct now in -pac and -monitor.
![pac](https://user-images.githubusercontent.com/47796546/53353691-e9f28a80-38ea-11e9-928a-3c163970f2ba.png)

![screenshot from 2019-02-25 10-46-55](https://user-images.githubusercontent.com/47796546/53353604-ba438280-38ea-11e9-932c-b9a1062f9b2b.png)

**Comment by Ricks-Lab** [comment]
Thanks for the verification!  This will be officially released in v2.1.0 soon.
