### ISSUE TITLE
monitor module:  --gui warning and column width

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#6]
In v. 2.0, the command <./amdgpu-monitor --gui > brings up this warning:

(amdgpu-monitor:23263): dbind-WARNING **: 15:05:23.731: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files.

..but the Gtk monitor window launches fine.

And here is a minor cosmetic issue:  I'm running an RX 460 and an RX 570. The columns in the monitor Gtk window are wide enough (self-adjusting?) to show all card information; in my case the card model name is a string of all AMD models that fall in the RX x60 (Baffin) or RX x70 & RX x80 (Ellesmere) series. The long string is fine (it does include the installed card), but when monitor is used only in the terminal window, <./amdgpu-monitor>, the columns for each card are too narrow to display the full model name(s), and may truncate before the installed model is seen. For example, the RX570 column only shows "RX 470/480/" .  Also the narrow column width can truncate the card's full performance mode name, e.g. 0-3D_FULL_SCREEN; and the first column needs to be 1 character wider to display all of "Power Cap (W)".  This is mostly eye-candy, but I raise it because the loss of card information in the terminal window may be confusing or misleading in some circumstances.

**Comment by Ricks-Lab** [comment]
The first warning message is not showing on my system, but google found this:
**[https://www.raspberrypi.org/forums/viewtopic.php?t=196070](url)**
Let me know if that has an effect for you.

I have made column width optimizations for amdgpu-monitor for both GUI and non-GUI options.  For my cards, the generation of short names from the long names works well.  Can you provide  exact long names and preferred short names?  Output of
      *amdgpu-ls | grep Model*
would be good.

**Comment by Ricks-Lab** [comment]
I am working in this branch:
[https://github.com/Ricks-Lab/amdgpu-utils/tree/v2.1.0-Features](url)

You can test, but there may be instabilities as I implement new features.

**Comment by csecht** [comment]
Ha, yes, from that link, I installed the recommended package on my Ubuntu 18.04 and the Python warning has disappeared.
sudo apt-get install at-spi2-core
Here are the long and short model names:

$ ./amdgpu-ls | grep Model
Card Model:  Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560] (rev cf)
Short Card Model:  RX 460/560D / Pro 450/455/460/555/560
Card Model:  Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev ef)
Short Card Model:  RX 470/480/570/570X/580/580X

My preferred short names are RX 460 and RX 570, but I don’t see how that can be known by the program from that output.

**Comment by csecht** [comment]
Yes, with 2.1.0-Features, the monitor columns in the terminal view work better.

**Comment by Ricks-Lab** [comment]
Optimizing GPU model names (short and long) will be added to my TODO list.

**Comment by Ricks-Lab** [comment]
@csecht  Hi Craig,  I am back to working on the Model name display issue.  I have found that there is a device ID that is probably used by other utilities to get an accurate Model Name.  I have not yet found a good source to decode device ID to model name, but I have built in my own conversion table.  Can you run the latest amdgpu-ls on master and let me know the device ID is shows and your preferred model name for both cards?

**Comment by Ricks-Lab** [comment]
I found a comprehensive PCI ID list.  Just need to write a routine to parse it.

**Comment by Ricks-Lab** [comment]
@csecht I have updated master with this capability.  It would be interesting to see if it works with your setup.

**Comment by csecht** [comment]
Here is the device and model info from -ls output for both cards. Card 1 should be "RX 460", Card 0 should be "RX 570".
$ ./amdgpu-ls
AMD Wattman features enabled: 0xffff7fff
amdgpu version: 18.50-708488
2 AMD GPUs detected
2 are Compatible

UUID: b5e2ce00de84476f9aa59cd084fafd79
Device ID: {'vendor': '0x1002', 'device': '0x67ef', 'subsystem_vendor': '0x103c', 'subsystem_device': '0x3421'}
Decoded Device ID: Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X]
Card Model:  Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560] (rev cf)
Short Card Model:  RX 460/560D / Pro 450/455/460/555/560
Display Card Model:  RX 460/560D / Pro 450/455/460/555/560
Card Number: 1
Card Path: /sys/class/drm/card1/device/
PCIe ID: 02:00.0
....
UUID: 561528b0a76344f69899c7217fd9208b
Device ID: {'vendor': '0x1002', 'device': '0x67df', 'subsystem_vendor': '0x1682', 'subsystem_device': '0xc570'}
Decoded Device ID: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
Card Model:  Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev ef)
Short Card Model:  RX 470/480/570/570X/580/580X
Display Card Model:  RX 470/480/570/570X/580/580X
Card Number: 0
Card Path: /sys/class/drm/card0/device/
PCIe ID: 01:00.0
....

**Comment by csecht** [comment]
Hi Rick,
Sorry, I didn’t check email until late in the day. I downloaded the new Master, ran -ls, and posted a reply comment in issue #6. The cards should come up as RX 460 (card1) and RX 570 (card0).

**Comment by Ricks-Lab** [comment]
For some reason, both cards are not listed at https://pci-ids.ucw.cz/  
I requested them to be added and updated the list I distribute.

**Comment by csecht** [comment]
Yes! That did it.
$ ./amdgpu-ls
....
UUID: 6d74a44fb28f4f398ca0c29bc708deb4
Device ID: {'vendor': '0x1002', 'device': '0x67ef', 'subsystem_vendor': '0x103c', 'subsystem_device': '0x3421'}
Decoded Device ID: Radeon RX 460
Card Model:  Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560] (rev cf)
Short Card Model:  RX 460/560D / Pro 450/455/460/555/560
Display Card Model: Radeon RX 460
Card Number: 1
Card Path: /sys/class/drm/card1/device/
PCIe ID: 02:00.0
....

UUID: 7583c1a321be492ea8eed696a7ad9fe8
Device ID: {'vendor': '0x1002', 'device': '0x67df', 'subsystem_vendor': '0x1682', 'subsystem_device': '0xc570'}
Decoded Device ID: Radeon RX 570
Card Model:  Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev ef)
Short Card Model:  RX 470/480/570/570X/580/580X
Display Card Model: Radeon RX 570
Card Number: 0
Card Path: /sys/class/drm/card0/device/
PCIe ID: 01:00.0
....

![monitor with new model name](https://user-images.githubusercontent.com/47796546/53607753-c0a15b00-3b85-11e9-8472-298f77fe3799.png)

**Comment by Ricks-Lab** [comment]
Feature available on master and is under preparation for v2.2.0 release.
