### ISSUE TITLE
<amdgpu-pac --execute_pac> error when setting fan speeds

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#7]
I tried the auto pac execution option to set fan speeds of both my cards at once, using Save All in the pac Gtk window.  Below is the terminal output. (Card1 is the RX 460, Card0 is RX 570.) This may be the same problem as the issue I just reported where manual execution of pac shell scripts does not change fan speeds, but here provides more information about the nature of the errors (?)

$ ./amdgpu-pac --execute_pac
AMD Wattman features enabled: 0xffff7fff
amdgpu version: 18.50-708488
2 AMD GPUs detected
2 are compatible

WARNING: Under Development
WARNING: Works but not fully tested.
Please report any bugs found.  Thanks!

Batch file completed: /home/craig/Desktop/amdgpu-utils-2.1.0-Features/pac_writer_8ef342bdb0fa4cca9bfe1de361976364.sh
Writing changes to GPU /sys/class/drm/card1/device/
+ sudo sh -c echo 1' >  /sys/class/drm/card1/device/hwmon/hwmon1/pwm1_enable
[sudo] password for craig: 
sh: 1: Syntax error: Unterminated quoted string
+ sudo sh -c echo '63' >  /sys/class/drm/card1/device/hwmon/hwmon1/pwm
sh: 1: cannot create /sys/class/drm/card1/device/hwmon/hwmon1/pwm: Permission denied
+ sudo sh -c echo 's 0 214 800' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 's 1 481 821' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 's 2 760 825' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 's 3 1020 925' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 's 4 1102 1012' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 's 5 1138 1056' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 's 6 1172 1100' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 's 7 1200 1143' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 'm 0 300 800' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 'm 1 1750 850' >  /sys/class/drm/card1/device/pp_od_clk_voltage
+ sudo sh -c echo 'auto' >  /sys/class/drm/card1/device/power_dpm_force_performance_level
+ sudo sh -c echo 'c' >  /sys/class/drm/card1/device/pp_od_clk_voltage

Batch file completed: /home/craig/Desktop/amdgpu-utils-2.1.0-Features/pac_writer_60c71cbf8a0444ce95eead142863da98.sh
Writing changes to GPU /sys/class/drm/card0/device/
+ sudo sh -c echo 1' >  /sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable
sh: 1: Syntax error: Unterminated quoted string
+ sudo sh -c echo '153' >  /sys/class/drm/card0/device/hwmon/hwmon0/pwm
sh: 1: cannot create /sys/class/drm/card0/device/hwmon/hwmon0/pwm: Permission denied
+ sudo sh -c echo 's 0 300 750' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 's 1 588 765' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 's 2 952 918' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 's 3 1076 1025' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 's 4 1143 1087' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 's 5 1208 1150' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 's 6 1250 1150' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 's 7 1286 1150' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 'm 0 300 750' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 'm 1 1000 800' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 'm 2 1750 900' >  /sys/class/drm/card0/device/pp_od_clk_voltage
+ sudo sh -c echo 'auto' >  /sys/class/drm/card0/device/power_dpm_force_performance_level
+ sudo sh -c echo 'c' >  /sys/class/drm/card0/device/pp_od_clk_voltage

^C
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1588, in main_quit
    @override(Gtk.main_quit)
KeyboardInterrupt

**Comment by csecht** [comment]
hmmm, not sure why my last sentence is in bold and larger font.  I used a # to set it off from the terminal output.

**Comment by Ricks-Lab** [comment]
Looks like I was missing a quote in setting pwm mode. Just made the change. Also had to make same fix for reset function.

**Comment by Ricks-Lab** [comment]
Hold off testing this. Just realized the I forgot to escape the quotes.

**Comment by Ricks-Lab** [comment]
@csecht Ok, now it should work.  Much more clear after some sleep.

**Comment by csecht** [comment]
Yes! Fan speeds can now be set. Once executed however, the new current % value is not often the same as the input value.  I assume that it is following some amdgpu table of preset values?  The displayed value also has 13 decimals. 
When trying to reset a fan back to its default setting, I realized that there is no option for doing that for just one parameter.  The Reset button changes all settings back to default, but it would be helpful to be able to also reset each individually.

**Comment by Ricks-Lab** [comment]
Could be that current value is based on pwm sensor signal where set value is the pwm sensor.  I suspect that there can be slight variation.  Are they at least close?  I think I have fixed it so the display of pwm is an integer.  It is always 0 on my system so please help to verify for me.  I also included the ability to reset fan and power cap by entering a negative value. 

I am now working on a new feature to set pstate mask.  This should have a significant impact on power management, as currently, max voltage is always used in the highest p-state.  Limiting to the second highest pstate should result in a significant power savings.

**Comment by csecht** [comment]
Yes! using a fan speed of -1 works very nicely to set fan control to automatic. That’s a nice feature. 
But something broke with that update because now current fan % speed is always displayed as 0 in the pac and monitor windows. I can enter and save fan values and I can tell they take by fan noise and temperature readouts, but actual speed %’s are not shown. 

I saw the pstate masking feature, but have not yet given it a shot.

i now use the *—execute_pac* option all the time because it provides fast response for changing settings (like when I mucked something up with fan speed and saw temps shooting up to 90+C).  Having the monitor window open in a separate terminal is essential when poking around in pac. 
It’s good that amdgpu-pac only allows setting fans with %; ROCm-smi allows using either % or state values with the —setfan option and I once made the mistake of entering a too-low state value because I forgot the % sign, which resulted in a system shutdown from an overheated card.

**Comment by Ricks-Lab** [comment]
I fixed the fan speed read problem.  To fix the 13 decimal display issue, I am converting to int, but the last version converted to int before multiplying by 100.  I am preparing for release and I wanted to include you in the credits for testing (--about).  Do you agree?  How should I refer to you (github handle, E@H handle, name, other)?

**Comment by csecht** [comment]
Yes, it looks good now.  I added screenshots of my latest pac and monitor windows to the fan issues comments in the Features branch. 

When I first downloaded and launched the latest versions of -monitor and -pac, the fan speed came up correctly for the rx570 (card0), but read zero for the rx460. Once I saved a value to change the rx460 fan, it then read correctly thereafter.  As far as I can tell, amdgpu-utils now works great!

Wow, yes, thanks for the credit.  Cool. Please use my E@H handle: cecht. You can also include my full name, Craig Echt - I don’t know what the usual GitHub conventions are. 

Cheers,
Craig

**Comment by Ricks-Lab** [comment]
Development and testing now complete.  Merged into master.
