### ISSUE TITLE
Current GUI Color Scheme not Readable in Ubuntu 20.04

### ISSUE THREAD

**Issue by Ricks-Lab** [Ricks-Lab/amdgpu-utils#75]
The gui apps' color scheme is not readable when using Ubuntu 20.04.  I have had the same issue with boinc manager.  I was considering changing it to a dark theme to eliminate the problem.  I have changed `amdgpu-monitor --gui`

Let me know what you think.

**Comment by csecht** [comment]
New color scheme looks good (better actually) on Ubuntu 18.04.4 LTS.

**Comment by Ricks-Lab** [comment]
I have modified the color schemes for plot, pac and monitor.  Let me know if you are able to check it out with 20.04.

**Comment by csecht** [comment]
I don't yet have 20.04, but noticed in 18.04 that pac launched from a remote host via ssh has all the entry fields highlighted as if selected, which makes dragging and selecting values a little challenging.  
It looks like this on a remote connection (with MLCK mask values selected):
![pac_from_ssh](https://user-images.githubusercontent.com/47796546/83309240-5f27cc00-a1ce-11ea-9379-f61da8b4a487.png)

 compared to how it looks locally, with the power cap value selected:
![pac_local](https://user-images.githubusercontent.com/47796546/83309313-8a122000-a1ce-11ea-9d6f-58f6fa69e8d6.png)

**Comment by Ricks-Lab** [comment]
What you are seeing via ssh is what I see when running in 20.04.  I have found a solution that has the default orange highlight when the background is green.  It now has the same look for both 18.04 and 20.04.  Let me know what you think.

**Comment by csecht** [comment]
Yes, that works.  All fields now have a green background both locally and remotely. Highlighting is orange locally and blue remotely via ssh.  Nice.
