### ISSUE TITLE
Bug in Master from 26 June 2020

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#91]
All amdgpu commands, except -chk, have this type of error:
```
~/Desktop/amdgpu-utils$ ./amdgpu-ls
Traceback (most recent call last):
  File "./amdgpu-monitor", line 47, in <module>
    __version__ = env.GUT_CONST.version
AttributeError: 'GutConst' object has no attribute 'version'
```

**Comment by Ricks-Lab** [comment]
In the latest on master, there should be no commands that begin with amd. They should all have the new names.

**Comment by KeithMyers** [comment]
Just to let you know I grabbed the new package from PyPi and installed them with no issues.  All worked as expected.

Available again for testing whenever you get Nvidia writing enabled in gpu-pac.  Just shoot me a message.

**Comment by csecht** [comment]
Dang those old habits of mine....
Closing this down.
